version: '3'
services: 
  reflector:
    build: .
    ports:
      - "1922:1922"
    depends_on:
      - "redis"
  redis:
    image: "redis:alpine"
    volumes:
      - .:/data
    ports:
      - "6379:6379"
